services:
    mongo:
        image: mongo
        container_name: mongo
        networks:
             - backend

    mirai:
        build: ./mirai
        container_name: mirai
        working_dir: "/mirai"
        volumes:
            - "./config/mirai:/mirai/config"
        networks:
            - frontend

    arxivaid:
        build: ./arxivaid
        container_name: arxivaid
        ports:
            - 80:80
        working_dir: "/arxivaid"
        volumes:
            - "./config/arxivaid:/arxivaid/config"
        networks:
            - frontend
            - backend
        depends_on:
            - mongo
            - mirai


networks:
    frontend:
    backend: